import type { Metadata } from 'next';
import type { ReactElement, ReactNode } from 'react';

import TopBar from '@/organisms/TopBar';
import { ThemeProvider } from '@/styles';
import GlobalStyle from '@/styles/GlobalStyle';

export const metadata: Metadata = {
  title: '',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactElement {
  return (
    <html>
      <head>
        {process.env.NODE_ENV === 'production' && (
          <base href="/realEstateDemo/" />
        )}
      </head>
      <body>
        <ThemeProvider>
          <GlobalStyle />
          <TopBar />
          {children}
          <div>...footer not yet implemented...</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
